# Generated by Django 6.0.4 on 2026-05-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helloworld", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["title"], name="book_title_idx"),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(fields=["due_date"], name="loan_due_idx"),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(fields=["return_date"], name="loan_return_idx"),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(fields=["checkout_date"], name="loan_checkout_idx"),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(fields=["age"], name="member_age_idx"),
        ),
    ]
